version: "3.7"

services:
    pocketbase:
        image: adisetiawan/pocketbase:0.23.7
        restart: unless-stopped
        ports:
            - 8080:8080
        volumes:
            - "./pb_data:/pb/pb_data"
